# Generated by Django 3.2.3 on 2021-05-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210525_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='descuento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(verbose_name='total orden'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('Aceptada', 'Aceptada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Nueva', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.IntegerField(max_length=13, verbose_name='monto pagado'),
        ),
    ]
