# Generated by Django 3.2.3 on 2021-05-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'ItemCarrito', 'verbose_name_plural': 'ItemCarritos'},
        ),
    ]
