# Generated by Django 3.2.3 on 2021-05-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variación', 'verbose_name_plural': 'Variaciones'},
        ),
    ]
