# Generated by Django 3.2.3 on 2021-05-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20210520_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationManager',
        ),
    ]
