# Generated by Django 3.2.3 on 2021-05-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_alter_variation_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_name', models.CharField(max_length=200, unique=True, verbose_name='nombre marca')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
