# Generated by Django 3.2.3 on 2021-05-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.marca', verbose_name='Marca'),
        ),
    ]
