# Generated by Django 3.2.3 on 2021-05-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_product_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tienda.marca', verbose_name='Marca'),
        ),
    ]
