# Generated by Django 3.2.3 on 2021-05-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_alter_product_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/products', verbose_name='imagenes'),
        ),
    ]
